In [3]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [4]:
import pandas as pd
import numpy as np

In [10]:
tabela1_cnpj = pd.read_csv('/content/drive/MyDrive/cnpjs_1.csv', delimiter=';')

<ipython-input-10-fb477b51e871>:1: DtypeWarning: Columns (10,23,25,29,31,32) have mixed types. Specify dtype option on import or set low_memory=False.
  tabela1_cnpj = pd.read_csv('/content/drive/MyDrive/cnpjs_1.csv', delimiter=';')

In [17]:
tabela1_cnpj.head(15)

,data,cnpj,cnpj_basico,cnpj_ordem,cnpj_dv,identificador_matriz_filial,nome_fantasia,situacao_cadastral,data_situacao_cadastral,motivo_situacao_cadastral,...,cep,ddd_1,telefone_1,ddd_2,telefone_2,ddd_fax,fax,email,situacao_especial,data_situacao_especial
0,2023-02-15,97253082000207,97253082,2,7,2,NaN,2,2009-12-21,0,...,96170000.0,53.0,32514497,53.0,32511843.0,53.0,32514497.0,objetivos@brturbo.com.br,NaN,NaN
1,2023-02-15,3151122000177,3151122,1,77,1,AQUARIUS RESTAURANTE,2,2022-03-31,0,...,96815770.0,51.0,7131133,NaN,NaN,51.0,7131133.0,suhma.alberto@viavale.com.br,NaN,NaN
2,2022-09-11,27738772000181,27738772,1,81,1,NaN,2,2005-11-03,0,...,29300765.0,28.0,35220832,28.0,35260666.0,28.0,35260666.0,fiscal@contabilidadeatac.com.br,NaN,NaN
3,2022-09-11,17096193000129,17096193,1,29,1,NaN,2,2012-10-31,0,...,44850000.0,74.0,99918904,NaN,NaN,NaN,NaN,capsulana@hotmail.com,NaN,NaN
4,2022-09-11,23202167000130,23202167,1,30,1,PIZZARIA GRANDE SABOR,2,2015-09-02,0,...,48960000.0,74.0,99290668,NaN,NaN,NaN,NaN,fortiscontabilidadedigital@gmail.com,NaN,NaN
5,2023-02-15,3468255000171,3468255,1,71,1,NaN,2,2005-11-03,0,...,40015300.0,71.0,2438442,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,2023-02-15,4268700000112,4268700,1,12,1,NaN,2,2005-11-03,0,...,23880000.0,21.0,6885365,NaN,NaN,21.0,6885365.0,NaN,NaN,NaN
7,2023-02-15,39953783000163,39953783,1,63,1,RESTAURANTE DA RO,2,2020-11-30,0,...,64607840.0,89.0,94151379,NaN,NaN,NaN,NaN,robertinhacortez@gmail.com,NaN,NaN
8,2023-02-15,39746302000149,39746302,1,49,1,PIZZARIA CENTRAL,2,2020-11-11,0,...,64795000.0,89.0,81062658,NaN,NaN,NaN,NaN,leonardo34678p@gmail.com,NaN,NaN
9,2023-02-15,18556963000131,18556963,1,31,1,ACOUGUE DUARTE,2,2013-07-25,0,...,68040060.0,93.0,92414960,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,2022-09-11,46370493000152,46370493,1,52,1,CANTINHO DA COMIDA CASEIRA,2,2022-05-12,0,...,85557000.0,46.0,84002749,NaN,NaN,NaN,NaN,prestesdaniel321@gmail.com,NaN,NaN
11,2022-11-24,43854362000152,43854362,1,52,1,LA CHAPA,2,2021-10-13,0,...,48870000.0,74.0,81246920,NaN,NaN,NaN,NaN,romarioamojesus2018@gmail.com,NaN,NaN
12,2021-12-24,18756711000156,18756711,1,56,1,O CHURRASQUEIRO,2,2013-08-26,0,...,69307725.0,95.0,91442989,NaN,NaN,NaN,NaN,adilane@rochaempreendimentos.com,NaN,NaN
13,2021-12-24,39360223000103,39360223,1,3,1,PURA VIDA,2,2020-10-08,0,...,69307725.0,95.0,81264473,NaN,NaN,NaN,NaN,iane-cardoso@hotmail.com,NaN,NaN
14,2021-12-24,42797231000118,42797231,1,18,1,RESTAURANTE DIANA COMIDAS CASEIRA,2,2021-07-20,0,...,69309180.0,95.0,91554824,NaN,NaN,NaN,NaN,diana.restaurante.rr@gmail.com,NaN,NaN

In [12]:
tabela1_cnpj.columns

Index(['data', 'cnpj', 'cnpj_basico', 'cnpj_ordem', 'cnpj_dv',
       'identificador_matriz_filial', 'nome_fantasia', 'situacao_cadastral',
       'data_situacao_cadastral', 'motivo_situacao_cadastral',
       'nome_cidade_exterior', 'id_pais', 'data_inicio_atividade',
       'cnae_fiscal_principal', 'cnae_fiscal_secundaria', 'sigla_uf',
       'id_municipio', 'id_municipio_rf', 'tipo_logradouro', 'logradouro',
       'numero', 'complemento', 'bairro', 'cep', 'ddd_1', 'telefone_1',
       'ddd_2', 'telefone_2', 'ddd_fax', 'fax', 'email', 'situacao_especial',
       'data_situacao_especial'],
      dtype='object')

In [15]:
tabela1_cnpj.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5474156 entries, 0 to 5474155
Data columns (total 33 columns):
 #   Column                       Dtype
---  ------                       -----
 0   data                         object
 1   cnpj                         int64
 2   cnpj_basico                  int64
 3   cnpj_ordem                   int64
 4   cnpj_dv                      int64
 5   identificador_matriz_filial  int64
 6   nome_fantasia                object
 7   situacao_cadastral           int64
 8   data_situacao_cadastral      object
 9   motivo_situacao_cadastral    int64
 10  nome_cidade_exterior         object
 11  id_pais                      float64
 12  data_inicio_atividade        object
 13  cnae_fiscal_principal        int64
 14  cnae_fiscal_secundaria       object
 15  sigla_uf                     object
 16  id_municipio                 float64
 17  id_municipio_rf              int64
 18  tipo_logradouro              object
 19  logradouro                   object
 20  numero                       object
 21  complemento                  object
 22  bairro                       object
 23  cep                          object
 24  ddd_1                        float64
 25  telefone_1                   object
 26  ddd_2                        float64
 27  telefone_2                   float64
 28  ddd_fax                      float64
 29  fax                          object
 30  email                        object
 31  situacao_especial            object
 32  data_situacao_especial       object
dtypes: float64(6), int64(9), object(18)
memory usage: 1.3+ GB

In [14]:
df_counts = pd.DataFrame(tabela1_cnpj)
value_counts_per_column = df_counts.apply(lambda x: x.value_counts())

print (value_counts_per_column)

                  data  cnpj  cnpj_basico  cnpj_ordem   cnpj_dv  \
0                  NaN   NaN          NaN         NaN  182338.0
1                  NaN   NaN          NaN   5325160.0   92164.0
2                  NaN   NaN          NaN     84058.0   90082.0
3                  NaN   NaN          NaN     19103.0   91121.0
4                  NaN   NaN          NaN      8073.0   91029.0
...                ...   ...          ...         ...       ...
ÁTICA              NaN   NaN          NaN         NaN       NaN
ÂNGELO GIUBERTI    NaN   NaN          NaN         NaN       NaN
ÂNGELO ROSENENTE   NaN   NaN          NaN         NaN       NaN
ÂNGELO TELES       NaN   NaN          NaN         NaN       NaN
ÂNGELO ZARDINE     NaN   NaN          NaN         NaN       NaN

                  identificador_matriz_filial  nome_fantasia  \
0                                         NaN            NaN
1                                   5325551.0            NaN
2                                    148605.0            NaN
3                                         NaN            NaN
4                                         NaN            NaN
...                                       ...            ...
ÁTICA                                     NaN            NaN
ÂNGELO GIUBERTI                           NaN            NaN
ÂNGELO ROSENENTE                          NaN            NaN
ÂNGELO TELES                              NaN            NaN
ÂNGELO ZARDINE                            NaN            NaN

                  situacao_cadastral  data_situacao_cadastral  \
0                                NaN                      NaN
1                                NaN                      NaN
2                          5474156.0                      NaN
3                                NaN                      NaN
4                                NaN                      NaN
...                              ...                      ...
ÁTICA                            NaN                      NaN
ÂNGELO GIUBERTI                  NaN                      NaN
ÂNGELO ROSENENTE                 NaN                      NaN
ÂNGELO TELES                     NaN                      NaN
ÂNGELO ZARDINE                   NaN                      NaN

                  motivo_situacao_cadastral  ...  cep   ddd_1  telefone_1  \
0                                 5474156.0  ...  NaN  5417.0      8799.0
1                                       NaN  ...  NaN   151.0       237.0
2                                       NaN  ...  NaN    46.0         NaN
3                                       NaN  ...  NaN    62.0         9.0
4                                       NaN  ...  NaN    95.0         NaN
...                                     ...  ...  ...     ...         ...
ÁTICA                                   NaN  ...  NaN     NaN         NaN
ÂNGELO GIUBERTI                         NaN  ...  NaN     NaN         NaN
ÂNGELO ROSENENTE                        NaN  ...  NaN     NaN         NaN
ÂNGELO TELES                            NaN  ...  NaN     NaN         NaN
ÂNGELO ZARDINE                          NaN  ...  NaN     NaN         NaN

                    ddd_2  telefone_2  ddd_fax     fax  email  \
0                 47163.0     47238.0   1092.0  1449.0    NaN
1                    14.0        60.0     47.0    46.0    NaN
2                     NaN        52.0      NaN    41.0    NaN
3                     NaN        41.0     14.0    33.0    NaN
4                     3.0         NaN     14.0     NaN    NaN
...                   ...         ...      ...     ...    ...
ÁTICA                 NaN         NaN      NaN     NaN    NaN
ÂNGELO GIUBERTI       NaN         NaN      NaN     NaN    NaN
ÂNGELO ROSENENTE      NaN         NaN      NaN     NaN    NaN
ÂNGELO TELES          NaN         NaN      NaN     NaN    NaN
ÂNGELO ZARDINE        NaN         NaN      NaN     NaN    NaN

                  situacao_especial  data_situacao_especial
0                               NaN                     NaN
1                               NaN                     NaN
2                               NaN                     NaN
3                               NaN                     NaN
4                               NaN                     NaN
...                             ...                     ...
ÁTICA                           NaN                     NaN
ÂNGELO GIUBERTI                 NaN                     NaN
ÂNGELO ROSENENTE                NaN                     NaN
ÂNGELO TELES                    NaN                     NaN
ÂNGELO ZARDINE                  NaN                     NaN

[3275787 rows x 33 columns]

In [16]:
tabela1_cnpj.corr()

<ipython-input-16-0ee8f44c0461>:1: FutureWarning: The default value of numeric_only in DataFrame.corr is deprecated. In a future version, it will default to False. Select only valid columns or specify the value of numeric_only to silence this warning.
  tabela1_cnpj.corr()

,cnpj,cnpj_basico,cnpj_ordem,cnpj_dv,identificador_matriz_filial,situacao_cadastral,motivo_situacao_cadastral,id_pais,cnae_fiscal_principal,id_municipio,id_municipio_rf,ddd_1,ddd_2,telefone_2,ddd_fax
cnpj,1.000000,1.000000,-0.019739,-0.001690,-0.109572,NaN,NaN,-0.622313,NaN,-0.030090,-0.022998,0.011097,-0.215358,-0.129045,-0.018594
cnpj_basico,1.000000,1.000000,-0.019739,-0.001690,-0.109572,NaN,NaN,-0.622313,NaN,-0.030090,-0.022998,0.011097,-0.215358,-0.129045,-0.018594
cnpj_ordem,-0.019739,-0.019739,1.000000,0.000790,0.193634,NaN,NaN,NaN,NaN,0.010759,0.014488,-0.007062,-0.037911,-0.020778,-0.009598
cnpj_dv,-0.001690,-0.001690,0.000790,1.000000,0.002673,NaN,NaN,0.006230,NaN,0.000768,0.000638,0.001034,-0.005225,-0.003539,-0.006562
identificador_matriz_filial,-0.109572,-0.109572,0.193634,0.002673,1.000000,NaN,NaN,NaN,NaN,0.021328,0.026229,-0.005538,0.040449,0.006243,-0.004029
situacao_cadastral,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
motivo_situacao_cadastral,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
id_pais,-0.622313,-0.622313,NaN,0.006230,NaN,NaN,NaN,1.000000,NaN,-0.001112,0.061346,-0.003766,NaN,NaN,NaN
cnae_fiscal_principal,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
id_municipio,-0.030090,-0.030090,0.010759,0.000768,0.021328,NaN,NaN,-0.001112,NaN,1.000000,0.862685,-0.098608,-0.218766,-0.050784,-0.054983
id_municipio_rf,-0.022998,-0.022998,0.014488,0.000638,0.026229,NaN,NaN,0.061346,NaN,0.862685,1.000000,-0.139040,-0.367232,-0.076223,-0.120183
ddd_1,0.011097,0.011097,-0.007062,0.001034,-0.005538,NaN,NaN,-0.003766,NaN,-0.098608,-0.139040,1.000000,-0.014111,-0.077769,0.616219
ddd_2,-0.215358,-0.215358,-0.037911,-0.005225,0.040449,NaN,NaN,NaN,NaN,-0.218766,-0.367232,-0.014111,1.000000,0.442497,0.371783
telefone_2,-0.129045,-0.129045,-0.020778,-0.003539,0.006243,NaN,NaN,NaN,NaN,-0.050784,-0.076223,-0.077769,0.442497,1.000000,0.073209
ddd_fax,-0.018594,-0.018594,-0.009598,-0.006562,-0.004029,NaN,NaN,NaN,NaN,-0.054983,-0.120183,0.616219,0.371783,0.073209,1.000000

In [18]:
tabela1_cnpj.isnull().sum()

data                                 0
cnpj                                 0
cnpj_basico                          0
cnpj_ordem                           0
cnpj_dv                              0
identificador_matriz_filial          0
nome_fantasia                   816240
situacao_cadastral                   0
data_situacao_cadastral          30870
motivo_situacao_cadastral            0
nome_cidade_exterior           5474031
id_pais                        5422998
data_inicio_atividade                0
cnae_fiscal_principal                0
cnae_fiscal_secundaria         1623482
sigla_uf                             0
id_municipio                       216
id_municipio_rf                      0
tipo_logradouro                  14451
logradouro                          14
numero                              51
complemento                    2948089
bairro                            2497
cep                                216
ddd_1                           202813
telefone_1                      202828
ddd_2                          4999075
telefone_2                     5000124
ddd_fax                        5039039
fax                            5038971
email                           910338
situacao_especial              5474144
data_situacao_especial         5474144
dtype: int64

In [19]:
tabela1_cnpj.nunique()

data                               14
cnpj                           515874
cnpj_basico                    504747
cnpj_ordem                        409
cnpj_dv                           100
identificador_matriz_filial         2
nome_fantasia                  344790
situacao_cadastral                  1
data_situacao_cadastral          6888
motivo_situacao_cadastral           1
nome_cidade_exterior                8
id_pais                            12
data_inicio_atividade           13532
cnae_fiscal_principal               1
cnae_fiscal_secundaria          68865
sigla_uf                           28
id_municipio                     5485
id_municipio_rf                  5486
tipo_logradouro                   291
logradouro                     182822
numero                          21285
complemento                     84162
bairro                          42421
cep                            251284
ddd_1                             139
telefone_1                     822459
ddd_2                              87
telefone_2                      30472
ddd_fax                           107
fax                             34093
email                          391506
situacao_especial                   1
data_situacao_especial              9
dtype: int64